### ISSUE TITLE
RetinaFaceAntiCov TRT Inference

### ISSUE THREAD

**Issue by xxxpsyduck** [SthPhoenix/InsightFace-REST#10]
Hello. I'm trying to use [this pretrained insightface model](https://github.com/deepinsight/insightface/tree/master/RetinaFaceAntiCov) with tensorrt. Successfully converted into trt format but having trouble when making predictions. I keep the original retina inference code. Maybe this model has different output shape then it causes an error:
```
File "/FaceRecognize/src/converters/modules/model_zoo/detectors/retinaface.py", line 322, in postprocess
    landmark_deltas = landmark_deltas.transpose((0, 2, 3, 1)).reshape((-1, 5, landmark_pred_len // 5))
ValueError: cannot reshape array of size 16320 into shape (5,0)
```
Could you please give me a hand to solve this?

**Comment by xxxpsyduck** [comment]
Update: [link](https://drive.google.com/drive/folders/1xwxWh1v4UcBYZ7oNTOorF8fyGqlz9mMW?usp=sharing) to converted model

**Comment by SthPhoenix** [comment]
Hi! RetinaFaceAntiCov has guiet different postprocessing code from original RetinaFace. Also its model has additional output for mask predictions.

You should first add proper output mapping to `src/converters/modules/configs.py`. Refer to `retinaface_outputs` as example. New outputs are labeled like **face_rpn_type_prob_reshape_stride**. 

Than you should add proper code for this output processing as in `retinaface_cov.py` in official repo to `src/converters/modules/model_zoo/detectors/retinaface.py`

**Comment by SthPhoenix** [comment]
> Update: [link](https://drive.google.com/drive/folders/1xwxWh1v4UcBYZ7oNTOorF8fyGqlz9mMW?usp=sharing) to converted model

BTW, sharing TensorRT models is pretty useless, since it's locked to hardware + TRT version

**Comment by xxxpsyduck** [comment]
@SthPhoenix hello. Can you kindly take a look at my fork? I updated config.py and retina.py but having the following error:
```
Traceback (most recent call last):
  File "detection_tester.py", line 61, in <module>
    detections = detector.detect(image.transformed_image, threshold=0.1)
  File "/app/modules/model_zoo/detectors/retinaface.py", line 284, in detect
    return self.postprocess(net_out, threshold, im_info)
  File "/app/modules/model_zoo/detectors/retinaface.py", line 332, in postprocess
    proposals = proposals[order, :]
IndexError: index 601 is out of bounds for axis 0 with size 600
```

**Comment by xxxpsyduck** [comment]
> > Update: [link](https://drive.google.com/drive/folders/1xwxWh1v4UcBYZ7oNTOorF8fyGqlz9mMW?usp=sharing) to converted model
> 
> BTW, sharing TensorRT models is pretty useless, since it's locked to hardware + TRT version

update it to onnx instead

**Comment by SthPhoenix** [comment]
> @SthPhoenix hello. Can you kindly take a look at my fork? I updated config.py and retina.py but having the following error:
> 
> ```
> Traceback (most recent call last):
>   File "detection_tester.py", line 61, in <module>
>     detections = detector.detect(image.transformed_image, threshold=0.1)
>   File "/app/modules/model_zoo/detectors/retinaface.py", line 284, in detect
>     return self.postprocess(net_out, threshold, im_info)
>   File "/app/modules/model_zoo/detectors/retinaface.py", line 332, in postprocess
>     proposals = proposals[order, :]
> IndexError: index 601 is out of bounds for axis 0 with size 600
> ```


Haven't tested it, but I can't find where you add output mappings for `mnet_cov2` in [configs.py](https://github.com/xxxpsyduck/InsightFace-REST/blob/master/src/converters/modules/configs.py)

it should be like this:

```python

anticonv_outputs =  [
                  'face_rpn_cls_prob_reshape_stride32',
                  'face_rpn_bbox_pred_stride32',
                  'face_rpn_landmark_pred_stride32',
                  'face_rpn_type_prob_reshape_stride32',
                  'face_rpn_cls_prob_reshape_stride16',
                  'face_rpn_bbox_pred_stride16',
                  'face_rpn_landmark_pred_stride16',
                  'face_rpn_type_prob_reshape_stride16',
                  'face_rpn_cls_prob_reshape_stride8',
                  'face_rpn_bbox_pred_stride8',
                  'face_rpn_landmark_pred_stride8',
                  'face_rpn_type_prob_reshape_stride8' 
                  ]

mxnet_models = {
   'mnet_cov2': {
        'symbol': 'mnet_cov2-symbol.json',
        'params': 'mnet_cov2-0000.params',
        'shape': (1, 3, 1080, 1920),
        'outputs':anticonv_outputs,
        'reshape': True,
        'in_package': False
    },
}
```

**Comment by xxxpsyduck** [comment]
@SthPhoenix I add those to config.py and the error still occurs :(

**Comment by SthPhoenix** [comment]
> @SthPhoenix I add those to config.py and the error still occurs :(

I'll try to check it later, but I think you have missed some model specific steps in postprocessing, I recall there were some changes in anchors building for anticov model

**Comment by SthPhoenix** [comment]
@xxxpsyduck, I have added support for mnet_cov2 in `src/converters`.

**Comment by xxxpsyduck** [comment]
@SthPhoenix Thank you for all the support!
