### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by alicera** [SthPhoenix/InsightFace-REST#11]
how to use insight2onnx.py 

python src/converters/modules/converters/insight2onnx.py 

Traceback (most recent call last):
  File "src/converters/modules/converters/insight2onnx.py", line 13, in <module>
    from .mx2onnx_conv import onnx as onnx_mxnet
ModuleNotFoundError: No module named '__main__.mx2onnx_conv'; '__main__' is not a package

**Comment by SthPhoenix** [comment]
Please use `src/converters/build_insight_trt.py` as example.

**Comment by alicera** [comment]
Is your cuda 11?

**Comment by SthPhoenix** [comment]
Yes, by default docker image is build upon TensorRT 20.09 docker image, which uses cuda 11 and require 450x nvidia drivers

**Comment by alicera** [comment]
problem 
I run the mnet_cov2 and it dont generate the onnx file in the folder

Command 
python src/converters/build_insight_trt.py 

The message 
mxnet version: 1.7.0
onnx version: 1.7.0
Converting MXNet model to ONNX...
[15:18:03] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[15:18:03] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
WARNING:root:Using an experimental ONNX operator: Crop. Its definition can change.
WARNING:root:Using an experimental ONNX operator: Crop. Its definition can change.
Building TensorRT engine...
[TensorRT] WARNING: [TRT]/home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: No implementation obeys reformatting-free rules, at least 13 reformatting nodes are needed, now picking the fastest path instead.
TensorRT model ready.

**Comment by SthPhoenix** [comment]
AFAIK model wasn't released yet, I have only tested Sub-center ArcFace

**Comment by alicera** [comment]
I try to run the  "python src/converters/build_insight_trt.py"  in the docker that you provide and it show the message.
Is the message normal?

mxnet version: 1.7.0
onnx version: 1.7.0
Converting MXNet model to ONNX...
[15:18:03] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[15:18:03] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
WARNING:root:Using an experimental ONNX operator: Crop. Its definition can change.
WARNING:root:Using an experimental ONNX operator: Crop. Its definition can change.
Building TensorRT engine...
[TensorRT] WARNING: [TRT]/home/jenkins/workspace/OSS/L0_MergeRequest/oss/parsers/onnx/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: No implementation obeys reformatting-free rules, at least 13 reformatting nodes are needed, now picking the fastest path instead.
TensorRT model ready.

**Comment by SthPhoenix** [comment]
First warning always fires for insightface models since they are trained using fp64 weights, it's normal.
Second warning fires if TensorRT detects that your GPU has fast FP16 support and builds engine with FP16 support. Haven't seen any side effects of this warning, so it's normal too.

**Comment by alicera** [comment]
Does it support 2d106det？
How use it？

**Comment by SthPhoenix** [comment]
This repository contains code to convert 2d106det model, but inference code is not yet implemented, since right now it have no actual use for face detection/recognition pipeline implemented in REST API.

**Comment by SthPhoenix** [comment]
> ok, thanks you
> Do you try the new model for Glint360k ?
> https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc

Added support for Glint360k models.

**Comment by SthPhoenix** [comment]
Closing for long inactivity.
