### ISSUE TITLE
Hash Mismatch

### ISSUE THREAD

**Issue by Sayyam-Jain** [SthPhoenix/InsightFace-REST#126]
Hi Thank you for the wonderful work. 
In the recognition models (Glintr100 & Arcface), there is a hash mismatch where it tries to download the model again resulting in incomplete download.

This results in protobuf errors. I downloaded the files manually and commented the following lines and the model compiled successfully. 
https://github.com/SthPhoenix/InsightFace-REST/blob/35abbb7e3400f96bdf8b5950e18eb32d03fede0a/src/api_trt/modules/model_zoo/getter.py#L111
https://github.com/SthPhoenix/InsightFace-REST/blob/35abbb7e3400f96bdf8b5950e18eb32d03fede0a/src/api_trt/modules/model_zoo/getter.py#L112

Can you please check. Thanks again

**Comment by SthPhoenix** [comment]
Hi! It's known issue with downloading models from some regions, where google drive might be inaccessible. Downloading models manually should fix the issue.
