### ISSUE TITLE
arcface: TensorRT model having lower accuracy than original mxnet model?

### ISSUE THREAD

**Issue by anil16007** [SthPhoenix/InsightFace-REST#14]
Plotting positive & negative pairs simiilarity-scores histogram, I am seeing some drop in accuracy of TensorRT model. Is anyone also seeing it

**Comment by SthPhoenix** [comment]
Hi! I haven't tested it that thoroughly, but it's really possible since model is converted.
Could you share more info please?

**Comment by SthPhoenix** [comment]
Closing for long inactivity. Feel free to reopen if you have any new info.
