### ISSUE TITLE
Issue running pipelinetest.py

### ISSUE THREAD

**Issue by bhargavravat** [SthPhoenix/InsightFace-REST#16]
hi @SthPhoenix : 

I followed all the steps , starting from creating docker to doing all the installation . ( Model download and conversion for both detection and recognition ) 

Upon completion of that while I am trying to run pipeline_tester.py file inside container I am getting this error : 
Can you please help me with this?

Traceback (most recent call last):
  File "pipeline_tester.py", line 18, in <module>
    faces = model.get(image)
  File "/app/modules/face_model.py", line 204, in get
    ret = [e for e in self.embed_faces(ret)]
  File "/app/modules/face_model.py", line 204, in <listcomp>
    ret = [e for e in self.embed_faces(ret)]
  File "/app/modules/face_model.py", line 132, in embed_faces
    embeddings = self.rec_model.get_embedding(crops)

**Comment by bhargavravat** [comment]
I just noticed that my detection is working as expected however I am facing issue with the recognition part!

**Comment by SthPhoenix** [comment]
Hi! Thanks for your feedback! 
I have used wrong function name `get_embeddings` instead of `get_embedding` in **trt_backend.py**.
Fixed this in latest commit.

**Comment by bhargavravat** [comment]
Hi @SthPhoenix : 

That solved it ! 
Thanks!!!
