### ISSUE TITLE
Inference Script for Converted Tensorrt Model

### ISSUE THREAD

**Issue by NaeemKhan333** [SthPhoenix/InsightFace-REST#2]
@SthPhoenix Thanks for nice work, I have converted the arcface model to tensorrt using your repository, can you provide the inferences script on input image for the converted tensorrt model. Thanks

**Comment by SthPhoenix** [comment]
I have inference scripts for both ArcFace and RetinaFace in testing right now, they both works, and will be uploaded with next push in day or two.

**Comment by NaeemKhan333** [comment]
@SthPhoenix can you provide it to me because I want to test the converted tensorrt model.Thanks

**Comment by SthPhoenix** [comment]
Added demo script `converters/insight_tester.py`, you can use it for reference.

**Comment by NaeemKhan333** [comment]
Thanks for Providing the Inferences Script, But I am getting this error while running

python3 insight_tester.py

Warming up TensorRT engine...
Traceback (most recent call last):
  File "insight_tester.py", line 25, in <module>
    model.prepare()
  File "/home/ubuntu/naeem/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_backend.py", line 11, in prepare
    self.rec_model.build()
  File "/home/ubuntu/naeem/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_loader.py", line 75, in build
    with open(self.engine_file, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime:
AttributeError: __enter__

**Comment by NaeemKhan333** [comment]
@SthPhoenix Thanks for Providing the Inferences Script, But I am getting this error while running

python3 insight_tester.py

Warming up TensorRT engine...
Traceback (most recent call last):
File "insight_tester.py", line 25, in
model.prepare()
File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_backend.py", line 11, in prepare
self.rec_model.build()
File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_loader.py", line 75, in build
with open(self.engine_file, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime:
AttributeError: enter

**Comment by SthPhoenix** [comment]
Which TensorRT version you are using?

**Comment by NaeemKhan333** [comment]
TensorRT 7.1.2

**Comment by SthPhoenix** [comment]
If you have changed default "/models" path in 
`config = Configs(models_dir="/models")` during conversion, you should also change this value in inference script

**Comment by NaeemKhan333** [comment]
@SthPhoenix I have change all the path, but getting the same error .

**Comment by NaeemKhan333** [comment]
@SthPhoenix I am using 

-> pycuda=2020.1
-> mxnet=1.6.0
-> insightface=0.1.5
-> Tensorrt=7.1.2
-> I am not using the Docker File, I am installing manually
-> I have cross check the path of every file, it is all good.
But geeting above error ,on this line of code

```
        with open(self.engine_file, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime:
            self.engine = runtime.deserialize_cuda_engine(f.read())
```

**Comment by NaeemKhan333** [comment]
@SthPhoenix is this could be the issue related to  FP16 , FP32 or FP64 type.

**Comment by SthPhoenix** [comment]
I'll check it, but it seems everything should work fine in your environment.
Aren't you using edge device like Jetson Nano?

**Comment by SthPhoenix** [comment]
> @SthPhoenix is this could be the issue related to FP16 , FP32 or FP64 type.

Script `build_insight_trt.py` uses fp32 by default,  so it should not be the case. Could you try changing
`TRT_LOGGER = trt.Logger()`
to
 `TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)`
And try running script again?

**Comment by NaeemKhan333** [comment]
> I'll check it, but it seems everything should work fine in your environment.
> Aren't you using edge device like Jetson Nano? I have no Jetsons to test it in this case.

I have Tesla K-80 Gpu, I donot have Jetson Neno for testing

**Comment by NaeemKhan333** [comment]
> > @SthPhoenix is this could be the issue related to FP16 , FP32 or FP64 type.
> 
> Script `build_insight_trt.py` uses fp32 by default, so it should not be the case. Could you try changing
> `TRT_LOGGER = trt.Logger()`
> to
> `TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)`
> And try running script again?

I have changed it, but got same error

**Comment by SthPhoenix** [comment]
And output before this error is the same? Aren't there any new logs?

**Comment by NaeemKhan333** [comment]
Getting Same Error,Dont have new log

**Comment by SthPhoenix** [comment]
Just to be sure, print output of this line:
`engine = config.build_model_paths(model_name,'plan')[1]`
in `insight_tester.py`, to ensure resulting path is the actual path to model

**Comment by NaeemKhan333** [comment]
@SthPhoenixI have checked the path,it all right, if path is the issue than ``no file or directory found error will be occure`` but it is not the case actully error is not related to path.

**Comment by NaeemKhan333** [comment]
I have given the absoulte path in conversion script to get the model at actual defined path 

But I am getting here the following error as well


$ python3 build_insight_trt.py
mxnet version: 1.6.0
onnx version: 1.7.0
Converting MXNet model to ONNX...
  Creating intermediate copy of source model...
  Applying RetinaFace specific fixes to input MXNet model before conversion...
  Exporting to ONNX...
[09:03:57] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
[09:03:57] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
  Applying ArcFace specific fixes to output ONNX
  Removing initializer from inputs in ONNX model...
  Removing intermediate *.symbol and *.params
Building TensorRT engine...
Traceback (most recent call last):
  File "build_insight_trt.py", line 54, in <module>
    prepare_insight_engine(mx_symbol, mx_params, output_onnx, output_engine, model_name, configs.mxnet_models_dir, force=True)
  File "build_insight_trt.py", line 33, in prepare_insight_engine
    convert_onnx(onnx_path, engine_path)
  File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/onnx_to_trt.py", line 39, in convert_onnx
    allow_fp16=allow_fp16)
  File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/onnx_to_trt.py", line 13, in _build_engine_onnx
    with trt.Builder(TRT_LOGGER) as builder, \
AttributeError: __enter__

**Comment by NaeemKhan333** [comment]
> I have given the absoulte path in conversion script to get the model at actual defined path
> 
> But I am getting here the following error as well
> 
> $ python3 build_insight_trt.py
> mxnet version: 1.6.0
> onnx version: 1.7.0
> Converting MXNet model to ONNX...
> Creating intermediate copy of source model...
> Applying RetinaFace specific fixes to input MXNet model before conversion...
> Exporting to ONNX...
> [09:03:57] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
> [09:03:57] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
> Applying ArcFace specific fixes to output ONNX
> Removing initializer from inputs in ONNX model...
> Removing intermediate *.symbol and *.params
> Building TensorRT engine...
> Traceback (most recent call last):
> File "build_insight_trt.py", line 54, in
> prepare_insight_engine(mx_symbol, mx_params, output_onnx, output_engine, model_name, configs.mxnet_models_dir, force=True)
> File "build_insight_trt.py", line 33, in prepare_insight_engine
> convert_onnx(onnx_path, engine_path)
> File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/onnx_to_trt.py", line 39, in convert_onnx
> allow_fp16=allow_fp16)
> File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/onnx_to_trt.py", line 13, in _build_engine_onnx
> with trt.Builder(TRT_LOGGER) as builder,
> AttributeError: **enter**

While I run with the `sudo`,Conversion is done sucessfully without giving any error.
$ sudo python3 build_insight_trt.py

mxnet version: 1.6.0
onnx version: 1.7.0
Converting MXNet model to ONNX...
  Creating intermediate copy of source model...
  Applying RetinaFace specific fixes to input MXNet model before conversion...
  Exporting to ONNX...
[09:15:25] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
[09:15:25] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
  Applying ArcFace specific fixes to output ONNX
  Removing initializer from inputs in ONNX model...
  Removing intermediate *.symbol and *.params
Building TensorRT engine...

[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT model ready.

**Comment by SthPhoenix** [comment]
And what about running inference as sudo?

I can't reproduce your errors, it seems to be somehow related to your environment. Actually if TensorRT managed to build and serialize engine, it should be able to run it.

**Comment by NaeemKhan333** [comment]
while I use the sudo in inferences script, it show me error of module not found like pycuda,although I have these modules in virtual environment but I think it is using parent module because of sudo .

**Comment by NaeemKhan333** [comment]
> while I use the sudo in inferences script, it show me error of module not found like pycuda,although I have these modules in virtual environment but I think it is using parent module because of sudo .

$ sudo python3 insight_tester.py
Traceback (most recent call last):
  File "insight_tester.py", line 10, in <module>
    from exec_backends.trt_backend import Arcface as InsightTRT
  File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_backend.py", line 1, in <module>
    from .trt_loader import TrtModel
  File "/home/ubuntu/user/InsightFace-REST/inf/InsightFace-REST/src/converters/exec_backends/trt_loader.py", line 1, in <module>
    import pycuda.driver as cuda
ModuleNotFoundError: No module named 'pycuda'

**Comment by NaeemKhan333** [comment]
> And what about running inference as sudo?
> 
> I can't reproduce your errors, it seems to be somehow related to your environment. Actually if TensorRT managed to build and serialize engine, it should be able to run it.

It build and serialize engine while I used `sudo` ,otherwise it is giving an error as I mentioned at top.

**Comment by SthPhoenix** [comment]
So if running script as sudo uses system libraries, and conversion works fine, and running it as user throws errors, might mean that there are some errors in your venv packages

**Comment by NaeemKhan333** [comment]
> So if running script as sudo uses system libraries, and conversion works fine, and running it as user throws errors, might mean that there are some errors in your venv packages

So If it could be the case, then It should work in inferences as well .

**Comment by SthPhoenix** [comment]
For inference your systems python interpreter missing pycuda

**Comment by NaeemKhan333** [comment]
But in virtual env,I have installed Pycuda

**Comment by NaeemKhan333** [comment]
Thanks , I get the results, I installed packages in root and do inferences with sudo and get the results.

$ sudo python3 insight_tester.py
Warming up TensorRT engine...
Engine warmup complete!
Expecting input shapes: [(1, 3, 112, 112)]
[09:56:31] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
[09:56:31] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!

1.0

**Comment by SthPhoenix** [comment]
1. When you run conversion script with venv interpreter - you got error.
2. When you run conversion script with system interpreter - everything works fine.
3. When you run inference with venv interpreter  - you got same error.
4. When you run inference with system interpreter  - you got missing package.

When you running with sudo, you are not using venv packages
