### ISSUE TITLE
Confuse about arcface_r100_v1.plan

### ISSUE THREAD

**Issue by NaeemKhan333** [SthPhoenix/InsightFace-REST#3]
@SthPhoenix I have converted the mxnet model to tensorrt model . I get the arcface_r100_v1.plan as a result, is it tensorrt model or something else becuase tensorrt model have extension .trt as I have seen on the repository

https://github.com/jkjung-avt/tensorrt_demos

Could you explain it for me.Thanks

**Comment by SthPhoenix** [comment]
Yes, it's the same, `.plan` extension was chosen because it's default TensorRT engine extension expected by Triton Inference Server

**Comment by NaeemKhan333** [comment]
@SthPhoenix How we can get inferences on the input images using this `.plan` file model.

**Comment by SthPhoenix** [comment]
Answered in #2
