### ISSUE TITLE
Accuracy loss ?

### ISSUE THREAD

**Issue by MyraBaba** [SthPhoenix/InsightFace-REST#31]
Hi,

Is there any accuracy decrease after conversion from standard model ?

**Comment by SthPhoenix** [comment]
I have noticed that ArcFace outputs are a bit different from MXNet model, though very close, similarity between MXNet embeddings and converted ONNX embeddings  is somewhere around 0.999998.

Outputs of ONNX and TRT models are exactly the same.

I haven't run any benchmarks on accuracy though, I'll appreciate if someone could check this.

**Comment by SthPhoenix** [comment]
Closing in favor of #34
