### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by alicera** [SthPhoenix/InsightFace-REST#32]
Hi SthPhoenix,

How to run the model  to onnx?
 https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc

thanks

**Comment by SthPhoenix** [comment]
Hi! You need to manually download `glint360k_r100FC_1.0` or `glint360k_r100FC_0.1` model and symbol files to `models/mxnet/glint360k_r100FC...` and change rec_model name to the model you selected. Both these models are supported.

**Comment by alicera** [comment]
1. mxnet model
It show the error
![image](https://user-images.githubusercontent.com/59388989/115962805-9b36ee80-a54f-11eb-917c-4f77f9a7fc26.png)


2. pytorch model 
Do you have the process the pt model tool?
https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch

**Comment by SthPhoenix** [comment]
1. That's correct, this model isn't part of original insightface python package, used for comparison.
2. I can't download it from baidu, so I can't check it )

**Comment by mkleshchenok** [comment]
> 2. I can't download it from baidu, so I can't check it )
You can download it [here](https://mega.nz/folder/ue52EJjS#laGVRDtos_rWuX6L6lzuYQ)

https://github.com/deepinsight/insightface/issues/1438#issuecomment-822030763

**Comment by SthPhoenix** [comment]
> > 1. I can't download it from baidu, so I can't check it )
> 
> You can download it [here](https://mega.nz/folder/ue52EJjS#laGVRDtos_rWuX6L6lzuYQ)
> 
> [deepinsight/insightface#1438 (comment)](https://github.com/deepinsight/insightface/issues/1438#issuecomment-822030763)

That's great! Thanks for the info, I'll check if I can convert it later.

**Comment by alicera** [comment]
I modify the model name "coordinateReg" in the insight_tester.py
But it show the message no this model
![image](https://user-images.githubusercontent.com/59388989/117573176-20ea9a80-b109-11eb-90fb-aa685419e345.png)

![image](https://user-images.githubusercontent.com/59388989/117573110-c2bdb780-b108-11eb-8e89-f013a34885ac.png)

**Comment by SthPhoenix** [comment]
Hi! As it's stated in readme coordinateReg can be converted, but it's inference is not supported.

**Comment by alicera** [comment]
I run the command "python insight_tester.py" and modify the model name "coordinateReg" in the insight_tester.py.
So the final result will get the onnx model but inference is not suppoerted.

By the way, do you know the coordinateReg project dataset ?

**Comment by SthPhoenix** [comment]
Closing. Added support for original `glintr100` model, based on PyTorch model.
