### ISSUE TITLE
Consfuion About the Inference Script

### ISSUE THREAD

**Issue by NaeemKhan333** [SthPhoenix/InsightFace-REST#4]
@SthPhoenix I have studied the inference script , So I get the following understanding
-> You are loading an input image
-> Preparing and loading the Tensorrt engine
-> Preparing and loading the orignal mxnet model
-> You are getting embedding the from both model
->  Then comparing the result of both model embedding.

Cqn you give me briefly explanation.It will be helpful because I want to show results on opencv windows .Thanks

**Comment by SthPhoenix** [comment]
This script is intended to check that output of TRT model is same/almost same with outputs from original model.
AcrFace model returns only face embeddings, suitable for identification/verification. 

If you need faces coordinates you need to use face detection algorithms like RetinaFace/MTCNN/CenterFace, etc.

**Comment by NaeemKhan333** [comment]
so we can remove the code of the orignal model embedding.it is not useful for us

**Comment by SthPhoenix** [comment]
yes
