### ISSUE TITLE
how to change diff. model in server?

### ISSUE THREAD

**Issue by u0251077** [SthPhoenix/InsightFace-REST#42]
first this repo. is awesome thx you~
but I don't know how to change
so that I can use different models to test

**Comment by SthPhoenix** [comment]
Hi! Thanks!
Just change `det_model` and `rec_model` parameters in `deploy_*.sh`  to one of models listed in comment string. BTW I highly recommend using `glintr100` recognition model in any scenario except when you need backward compatibility.

**Comment by u0251077** [comment]
thx you
