### ISSUE TITLE
When i use plan in Triton Inference Server get a error

### ISSUE THREAD

**Issue by 17702513221** [SthPhoenix/InsightFace-REST#49]
Can you help me how to transfet model to Triton Inference Server
Can you tell me when have Triton Inference Server examples

**Comment by 17702513221** [comment]
during loading ,I have a error use InsightFace-REST's plan's model.
I try to use trtexec change onnx to trt,I have a error

**Comment by 17702513221** [comment]
![1](https://user-images.githubusercontent.com/40785359/128959746-cf2c232e-53f0-4c5f-8ffa-c787d3812b9f.jpg)
![2](https://user-images.githubusercontent.com/40785359/128959750-1908f5b8-b67e-4bb5-973f-fe7c1bde59ca.jpg)
![3](https://user-images.githubusercontent.com/40785359/128959751-0e014f50-0683-4fae-a1e4-7e1cfe86ec39.jpg)
![4](https://user-images.githubusercontent.com/40785359/128959753-010717e7-fd4d-49c3-b466-7578b1f6af10.jpg)
1 is my yolov4 tensorrt's model and insightFace-REST's plan's model,The type is difference.
2 is when i try to use it in triton's error
3 is my try to use trtexec change onnx to tensorrt
4 is my change code
my sdk is tensorrt 21.04 triton is 21.06

**Comment by SthPhoenix** [comment]
Yes, that's exactly the same problem I encountered with SCRFD in Triton server.
InstanceNormalizationPlugin fails to load in Triton.

 In python version of TensorRT this can be fixed by calling `trt.init_libnvinfer_plugins(None, "")`  before loading models, but I wasn't able to find corresponding parameter in Triton server.

BTW, TRT and Triton versions should match to guarantee compatibility.

**Comment by SthPhoenix** [comment]
As for your screenshot 4, actual input name is `input.1`
so you should provide shapes like `input.1:1x3x640x640`

**Comment by 17702513221** [comment]
./trtexec --onnx=/workspace/face/models/onnx/scrfd_10g_gnkps/scrfd_10g_gnkps.onnx --minShapes=input.1:1x3x640x640 --optShapes=input.1:1x3x640x640 --maxShapes=input.1:1x3x640x640 --explicitBatch  --saveEngine=/workspace/face/models/onnx/scrfd_10g_gnkps/scrfd_10g_gnkps.trt --fp16
I success,next i want to try detect
