### ISSUE TITLE
how to use triton_backend

### ISSUE THREAD

**Issue by 17702513221** [SthPhoenix/InsightFace-REST#50]
![92408fa5ef2a00d82facbb4d36a6df6](https://user-images.githubusercontent.com/40785359/129029087-aa115108-02fc-46cd-a07c-10650e5bec83.jpg)
Like this,can you tell me how to use triton_backend to deal with results

**Comment by SthPhoenix** [comment]
Have you found the solution?

**Comment by 17702513221** [comment]
![d2f022fb8d1917563ae03247d0d9c50](https://user-images.githubusercontent.com/40785359/129295313-0ada5346-304b-487a-8176-3df677b7c205.jpg)
I success in your triton_backend and detection_tester,now i try to deal with system_shared_memory.

**Comment by SthPhoenix** [comment]
Have you modified `triton_backend.py` to correctly run scrfd? 
For some reason `.plan` generated with python requires to manually configure Triton server and some workaround in `triton_backend.py` (I have committed this workaround yesterday)

**Comment by 17702513221** [comment]
sorry,I test retinaface_r50_v1 and arcface_r100_v1 is right.
I use trtexec success
