### ISSUE TITLE
What's the different between retinaface_mnet025 V1 and V2?

### ISSUE THREAD

**Issue by jackgao0323** [SthPhoenix/InsightFace-REST#52]
Hi,
I only see one model on InsightFace github. I'm curious about the model on InsightFace is which version and what's the different between V1 and V2.

**Comment by SthPhoenix** [comment]
Hi! These models were part of `insightface<=0.1.5` python package.

I can't find link right now, but @nttstar, somewhere explained that v2 was more accurate in terms of key points detection, while v1 was less accurate but was able to detect more faces.

Anyway, for now I recommend using `scrfd_500g` or `scrfd_2.5m` family models as more accurate than `retinaface_mnet025`.

There are two versions in this repo: 
1. original `scrfd_*_bnkps`, which is a bit more accurate, but have issues with large faces occupying most of the image.
2. `scrfd_*_gnkps` - version I have retrained for this repo, it doesn't have issues with large faces at cost of a some accuracy.

**Comment by jackgao0323** [comment]
Thanks a lot. I'll give it a try!
