### ISSUE TITLE
Are you plans to update WebFace related models in the future?

### ISSUE THREAD

**Issue by u0251077** [SthPhoenix/InsightFace-REST#55]
First, very thanks you contribute, this repo. help me a lot.
WebFace compared to glint360k seems to have better performance on IFRT dataset.
Are you plans to update WebFace related models in the future?

**Comment by SthPhoenix** [comment]
Hi! AFAIK now there is only Resnet50 version trained with WebFace600K, which is almost twice faster than default glintr100 model,  but with a bit lower accuracy.
 
Though comparing to other r50 based models  WebFace version indeed performs better. 

I have now support for WebFace600K model from insightface model zoo, though for now it must be manually downloaded and placed to `models/onnx/webface_r50/webface_r50.onnx`
