### ISSUE TITLE
No module named 'cupy'

### ISSUE THREAD

**Issue by tonhathuy** [SthPhoenix/InsightFace-REST#61]
![image](https://user-images.githubusercontent.com/45118883/143766850-86948451-5dd1-420f-936a-592b719db8a1.png)
I got a bug `No module named 'cupy'` when run deploy_cpu.sh , I try to run `pip install cupy `but it can't install

**Comment by SthPhoenix** [comment]
Hi! Cupy isn't required for CPU version. 
FastAPI for some reason throws errors after logging warning message, but should work as intended.

**Comment by SthPhoenix** [comment]
Should be fixed with cf64b7e8d9109982974597834548ee821f1f538f
