### ISSUE TITLE
cv2.error: OpenCV(4.5.4)

### ISSUE THREAD

**Issue by celalettinbilgen** [SthPhoenix/InsightFace-REST#62]
Hi, 

I am using cpu container. I am getting an error as below. What would your suggestion be about this?

![image](https://user-images.githubusercontent.com/13656331/147615614-c9281e39-ecaa-4338-b793-2827a43ebebb.png)

**Comment by SthPhoenix** [comment]
Hi! I need some time to investigate the issue. This specific issue can be easily fixed, but new issues related to onnxruntime arise after fixing it.

**Comment by SthPhoenix** [comment]
Well other issues I was talking about seems to be related to numba cache left from GPU version when I was running tests.
