### ISSUE TITLE
adding middleware cause errors

### ISSUE THREAD

**Issue by MyraBaba** [SthPhoenix/InsightFace-REST#69]
Adding middleware cause errors after a while running test (demo_client.py).

app gives error:

`h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
`

**Comment by MyraBaba** [comment]
Sorry:

Put a middleware to app

İe:

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    logger.info('Some use ful information...')
    idem = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
    logger.info(f"rid={idem} start request path={request.url.path}")
    start_time = time.time()
    response = await call_next(request)
    process_time = (time.time() - start_time) * 1000
    formatted_process_time = '{0:.2f}'.format(process_time)
    logger.info(f"rid={idem} completed_in={formatted_process_time}ms status_code={response.status_code}")
    process_time = time.time() - start_time
    response.headers["Xz-Process-Time"] = str(process_time)
    return response


Than run demo_client for benchmark.

You will see the errors in a while

**Comment by SthPhoenix** [comment]
I'll try to investigate on this issue, though it'll took some time since it's out of scope of the project.

**Comment by MyraBaba** [comment]
thx. no worries.

**Comment by SthPhoenix** [comment]
Actually that's turns out that this issue has nothing to do with your middleware. 
This seems to be bug I have noticed few times when oversaturating API with requests (threads in demo client) or sending large images which requires longer processing.  
It seems to be related to default uvicorn keep-alive timeout, which is 5 seconds.
You can try fixing it by increasing this timeout in entrypoint.sh by adding --timeout-keep-alive 20000 argument to uvicorn server. It'll increase timeout to 20s.

**Comment by MyraBaba** [comment]
It is UVICORN_TIMEOUT-KEEP-ALIVE=20000 right according to https://www.uvicorn.org/settings/ ?

Best

**Comment by MyraBaba** [comment]
Still error even timeout 20sec through env settings

**Comment by MyraBaba** [comment]
Now looks ok with :  uvicorn.run("app:app", host="0.0.0.0", port=18081 , reload=True , log_level="debug" , timeout_keep_alive=20000)

**Comment by SthPhoenix** [comment]
In my case I have just changed last line in entrypoint.sh to:
```
uvicorn app:app --port 18080 --host 0.0.0.0 --workers $NUM_WORKERS --timeout-keep-alive 20000
```
