### ISSUE TITLE
Automatic download of glintr100.onnx fails

### ISSUE THREAD

**Issue by bwmcin** [SthPhoenix/InsightFace-REST#72]
It appears that the glintr100.onnx file that is downloaded is actual HTML stating that the file it to big for virus scan and requests input to ok the download.  I manually downloaded the file and all works.

**Comment by SthPhoenix** [comment]
It's known issue, fix will be uploaded shortly. 
It seems that approximately week or two ago Google have changed download workflow

**Comment by SthPhoenix** [comment]
Fixed with #73
