### ISSUE TITLE
Docker build fails due to "unauthenticated git protocol on port 9418 is no longer supported"

### ISSUE THREAD

**Issue by felixdollack** [SthPhoenix/InsightFace-REST#78]
The dependency PyTurboJPEG is installed with the no longer supported unauthenticated git protocol.

Changing the repository address in Dockerfile_* fixes the issue for me though.

-RUN $PIP_INSTALL git+git://github.com/lilohuang/PyTurboJPEG.git msgpack
+RUN $PIP_INSTALL git+https://github.com/lilohuang/PyTurboJPEG.git msgpack

**Comment by SthPhoenix** [comment]
Thanks! I have merged your commit.
Though that's strange, I recall building from scratch 2-3 weeks ago without any issues, but google suggest this issue exists since January.
