### ISSUE TITLE
Batch inference with recognition model

### ISSUE THREAD

**Issue by xxxpsyduck** [SthPhoenix/InsightFace-REST#8]
Hi. In an image in which face detector detects multiple faces, I want to feed all of them to the recognition model at once instead of one by one using a for loop. I'm using trt backend. Can you give me a guide for doing that?

**Comment by SthPhoenix** [comment]
Hi! I am working on this issue. Haven't figured out full solution yet, but you can refer to commented lines in [onnx_to_trt.py](https://github.com/SthPhoenix/InsightFace-REST/blob/master/src/api_trt/modules/converters/onnx_to_trt.py). 

Also ONNX must have batch dimension N set to -1, you can change it in [reshape_onnx.py](https://github.com/SthPhoenix/InsightFace-REST/blob/master/src/api_trt/modules/converters/reshape_onnx.py#L6).

Required steps to enable batch processing are the following:
1. Set batch dimension in ONNX to -1.
2. Set explicit batch during building TRT engine (already set)
3. Add optimization profiles to engine config during building.

For step 3 you should uncomment lines in onnx_to_trt.py, and change `build_cuda_engine` to `build_engine`, which supports passing build configs.

I was able to build engine with following steps, but wasn't able to run batch inference with it, though I haven't spent much efforts for this yet.

Feel free to post your solution if you manage to accomplish this.

**Comment by SthPhoenix** [comment]
Looks like this [gist](https://gist.github.com/rmccorm4/dabccb1f31dbdcf1019a4df431067e52) might have relevant information

**Comment by SthPhoenix** [comment]
I have updated converters to allow building TRT models supporting different batch sizes, you can refer to [build_insight_trt.py](https://github.com/SthPhoenix/InsightFace-REST/blob/master/src/converters/build_insight_trt.py) for example.

I haven't updated inference scripts to support different batch sizes yet, but it looks like Triton Inference Server works with engine produced by updated script and supports batching, which indicates that engine builds properly at least.

**Comment by xxxpsyduck** [comment]
@SthPhoenix Thank you
