### ISSUE TITLE
Can I use it on CPU only?

### ISSUE THREAD

**Issue by martinenkoEduard** [SthPhoenix/InsightFace-REST#90]
Can I use it on CPU only?

**Comment by SthPhoenix** [comment]
Yes, just run it with `deploy_cpu.sh`

**Comment by leruge** [comment]
我使用cpu启动提示我
ModuleNotFoundError: No module named 'onnxruntime'
是需要自己安装'onnxruntime'？

**Comment by SthPhoenix** [comment]
Previously `onnxruntime` was a dependency of `onnx-simplifier` and was installed with it, looks like now it should be specified in `requirements.txt` directly. I'll fix it right now.
