### ISSUE TITLE
trt batch infer results error

### ISSUE THREAD

**Issue by yuxianmin** [SthPhoenix/InsightFace-REST#91]
Use trt backend, max_batch_size 2 for test. 
When I perform inference with a single image, the return result is correct, but if two different images are input together, the second image will have wrong detections; but if the two images are same, the results are correct

What could be the reason for this? thanks

some errors for example, use scrfd_500m_bnkps_640_640_batch2.plan
1. when use 
[
  "test_images/Stallone.jpg",
  "test_images/mask.jpg"
]

![image](https://user-images.githubusercontent.com/93767988/178460327-5e4e1fb5-83dd-4739-a75d-8e6c9417193d.png)

2. when use 
[
"test_images/mask.jpg",
"test_images/lumia.jpg",
]

![image](https://user-images.githubusercontent.com/93767988/178460602-cde970f9-997f-4b6e-9bda-f94d4d13b118.png)

**Comment by SthPhoenix** [comment]
Hi! that's interesting, could you please run the same test with `yolov5s-face` model to narrow down the issue?

**Comment by SthPhoenix** [comment]
Should be working now )

**Comment by yuxianmin** [comment]
Thanks for replying so quickly.
In addition to this offset problem, there may be another problem that needs to be changed.

self.score_list/bbox_list/kpss_list will be overwritten by the following image, resulting in an error in the previous image

![image](https://user-images.githubusercontent.com/93767988/178642752-4f19d58b-7ef5-4d9e-aedc-1de503fc2028.png)

**Comment by SthPhoenix** [comment]
Actually those arrays aren't reset intentionally, I found that reallocating them might noticably impact performance, so I have allocated memory during initialization and then just assigning new values.

What kind of errors you have with first image? I'll investigate it more thoroughly.

**Comment by yuxianmin** [comment]
If it is not reset, because different images share these arrays,  when the offset starts from 0 during the batch cycle, the previous detection data will be overwritten by the latter

for two images, batch=2

[
"test_images/mask.jpg",
"test_images/lumia.jpg",
]
![image](https://user-images.githubusercontent.com/93767988/178664675-a79c6896-e279-4767-a3ab-24fb80c55afa.png)

**Comment by SthPhoenix** [comment]
Yes, I can reproduce this behavior too. Array slices are passed to output by reference instead of value, I'll fix it shortly.
Thanks for pointing out the issue!

**Comment by yuxianmin** [comment]
By the way, ask a question.  When using batch inference (eg: scrfd_500m_bnkps.onnx) under gpu with onnxruntime-gpu, the batch inference time(only the inference time, not include pre and post process) is basically not improved. Have you encountered it? The model is also running on the gpu.
thanks

**Comment by SthPhoenix** [comment]
> By the way, ask a question. When using batch inference (eg: scrfd_500m_bnkps.onnx) under gpu with onnxruntime-gpu, the batch inference time(only the inference time, not include pre and post process) is basically not improved. Have you encountered it? The model is also running on the gpu. thanks

I haven't added batch inference for onnxruntime, so it should be processing images one by one.

 I remember there were some issues with batch inference enabled and using onnxruntime on CPU, though I can't recall if there were any issues on GPU.

**Comment by yuxianmin** [comment]
okay, thanks for your reply!
