### ISSUE TITLE
post numpy array to server

### ISSUE THREAD

**Issue by yuxianmin** [SthPhoenix/InsightFace-REST#92]
hi, 
 ask a question, how to post cv numpy array list directly to fastapi？
 currently, I encode the cv array to base64. In some scenarios, base64 encoding take some time.

 thanks.

**Comment by SthPhoenix** [comment]
Hi! You can use msgpack as quick replacement for json, it can serialize binary data. Though image decoded to numpy array might be pretty heavy, so transfer overhead may neglect benefits of decoding image in separate process, if I understand your use case correctly.

**Comment by yuxianmin** [comment]
Yeah, thank you so much for your suggestion.
