### ISSUE TITLE
CPU运行报错

### ISSUE THREAD

**Issue by leruge** [SthPhoenix/InsightFace-REST#95]
FileNotFoundError: [Errno 2] No such file or directory: '/models/onnx/scrfd_2.5g_gnkps/scrfd_2.5g_gnkps.onnx'
这些文件是从哪里下载的？

**Comment by SthPhoenix** [comment]
Models are automatically downloaded from Google drive.
Are you trying to run this repo without docker?

**Comment by leruge** [comment]
如果自动下载不成功，有手动下载的地方吗？

**Comment by leruge** [comment]
自动下载失败的话，可以手动下载吗？手动下载的都是onnx文件呀，要如何配置，有相关教程吗？

**Comment by SthPhoenix** [comment]
You can manually download models from https://github.com/SthPhoenix/InsightFace-REST#list-of-supported-models

Models should be placed under following path:
`<root_dir>/onnx/<model_name>/<model_name>.onnx`

**Comment by leruge** [comment]
非常感谢您的回答，不使用缓存构建docker镜像就可以了，稍后我也试一下手动下载。

**Comment by leruge** [comment]
问题已解决。
`docker build -t $IMAGE:$TAG -f src/Dockerfile_cpu src/.`换成`docker build --no-cache -t $IMAGE:$TAG -f src/Dockerfile_cpu src/.`
在 `deploy_cpu.sh`的75行

**Comment by leruge** [comment]
> 非常感谢您的回答，不使用缓存构建docker镜像就可以了，稍后我也试一下手动下载。

手动下载的文件只需要放进去可以使用，我还以为要进行很复杂的操作呢。

**Comment by SthPhoenix** [comment]
> > 非常感谢您的回答，不使用缓存构建docker镜像就可以了，稍后我也试一下手动下载。
> 
> 手动下载的文件只需要放进去可以使用，原来如此简单，构建镜像卡了我好几天。

Glad you managed to solve this issue!
