### ISSUE TITLE
人脸检测、对齐、识别

### ISSUE THREAD

**Issue by leruge** [SthPhoenix/InsightFace-REST#96]
restapi中没有直接提供检测、对齐和识别的三个接口吗？我应该这么实现这些接口？

**Comment by SthPhoenix** [comment]
I'm not sure I understand you correctly.

You can use rest API to run:
1. Detection only
2. Embedding previously cropped faces
3. Returning aligned faces 

It all works out of the box without modifying anything, you should just adjust request parameters to fit your use case.

**Comment by SthPhoenix** [comment]
This API is intended for detection of faces and extraction of face embeddings, which can be further used for recognition.
 Recognition must be implemented on you side, you can look at FAISS or Milvus for indexing and searching embeddings, or just compare embeddings using cosine similarity or inner product.

**Comment by leruge** [comment]
谢谢，明白了，那我试着实现一下。
